### ISSUE TITLE
m1运行不了

### ISSUE THREAD

**Issue by jesse996** [xiaozhuai/odourless#7] opened 2021-10-31 05:07 UTC
```
❯ uname -a
Darwin jesseMacBook-Air.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64
```
arm64 ,arm64e都运行不了

**Comment by xiaozhuai** [comment] 2021-11-02 07:49
@jesse996 duplicate of #6

**Closed by xiaozhuai** 2021-11-02 07:49 UTC
Labels: duplicate
